services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5437:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  pkmis:
    build:
      context: ./pkmis
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET=${SECRET}
      - ADMIN_DEFAULT_USERNAME=${ADMIN_DEFAULT_USERNAME}
      - ADMIN_DEFAULT_EMAIL=${ADMIN_DEFAULT_EMAIL}
      - ADMIN_DEFAULT_PASSWORD=${ADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped

volumes:
  postgres-data:
  pgadmin-data: